// ESPN CDN team logo URLs
// Format: https://a.espncdn.com/i/teamlogos/{sport}/500/{abbr}.png

import { getCountryFlagUrl } from './countryFlag'

const NHL_ABBRS = {
  'Anaheim Ducks': 'ana', 'Arizona Coyotes': 'ari', 'Boston Bruins': 'bos',
  'Buffalo Sabres': 'buf', 'Calgary Flames': 'cgy', 'Carolina Hurricanes': 'car',
  'Chicago Blackhawks': 'chi', 'Colorado Avalanche': 'col', 'Columbus Blue Jackets': 'cbj',
  'Dallas Stars': 'dal', 'Detroit Red Wings': 'det', 'Edmonton Oilers': 'edm',
  'Florida Panthers': 'fla', 'Los Angeles Kings': 'la', 'Minnesota Wild': 'min',
  'Montreal Canadiens': 'mon', 'Montréal Canadiens': 'mon',
  'Nashville Predators': 'nsh', 'New Jersey Devils': 'njd',
  'New York Islanders': 'nyi', 'New York Rangers': 'nyr', 'Ottawa Senators': 'ott',
  'Philadelphia Flyers': 'phi', 'Pittsburgh Penguins': 'pit', 'San Jose Sharks': 'sj',
  'Seattle Kraken': 'sea', 'St. Louis Blues': 'stl', 'St Louis Blues': 'stl',
  'Tampa Bay Lightning': 'tb', 'Toronto Maple Leafs': 'tor',
  'Utah Hockey Club': 'uta', 'Utah Mammoth': 'uta',
  'Vancouver Canucks': 'van', 'Vegas Golden Knights': 'vgk', 'Washington Capitals': 'wsh',
  'Winnipeg Jets': 'wpg',
}

const NBA_ABBRS = {
  'Atlanta Hawks': 'atl', 'Boston Celtics': 'bos', 'Brooklyn Nets': 'bkn',
  'Charlotte Hornets': 'cha', 'Chicago Bulls': 'chi', 'Cleveland Cavaliers': 'cle',
  'Dallas Mavericks': 'dal', 'Denver Nuggets': 'den', 'Detroit Pistons': 'det',
  'Golden State Warriors': 'gs', 'Houston Rockets': 'hou', 'Indiana Pacers': 'ind',
  'LA Clippers': 'lac', 'Los Angeles Clippers': 'lac', 'Los Angeles Lakers': 'lal',
  'LA Lakers': 'lal', 'Memphis Grizzlies': 'mem', 'Miami Heat': 'mia',
  'Milwaukee Bucks': 'mil', 'Minnesota Timberwolves': 'min', 'New Orleans Pelicans': 'no',
  'New York Knicks': 'ny', 'Oklahoma City Thunder': 'okc', 'Orlando Magic': 'orl',
  'Philadelphia 76ers': 'phi', 'Phoenix Suns': 'phx', 'Portland Trail Blazers': 'por',
  'Sacramento Kings': 'sac', 'San Antonio Spurs': 'sa', 'Toronto Raptors': 'tor',
  'Utah Jazz': 'utah', 'Washington Wizards': 'wsh',
}

const MLB_ABBRS = {
  'Arizona Diamondbacks': 'ari', 'Atlanta Braves': 'atl', 'Baltimore Orioles': 'bal',
  'Boston Red Sox': 'bos', 'Chicago Cubs': 'chc', 'Chicago White Sox': 'chw',
  'Cincinnati Reds': 'cin', 'Cleveland Guardians': 'cle', 'Colorado Rockies': 'col',
  'Detroit Tigers': 'det', 'Houston Astros': 'hou', 'Kansas City Royals': 'kc',
  'Los Angeles Angels': 'laa', 'Los Angeles Dodgers': 'lad', 'Miami Marlins': 'mia',
  'Milwaukee Brewers': 'mil', 'Minnesota Twins': 'min', 'New York Mets': 'nym',
  'New York Yankees': 'nyy', 'Oakland Athletics': 'oak', 'Athletics': 'oak', 'Philadelphia Phillies': 'phi',
  'Pittsburgh Pirates': 'pit', 'San Diego Padres': 'sd', 'San Francisco Giants': 'sf',
  'Seattle Mariners': 'sea', 'St. Louis Cardinals': 'stl', 'St Louis Cardinals': 'stl',
  'Tampa Bay Rays': 'tb', 'Texas Rangers': 'tex', 'Toronto Blue Jays': 'tor',
  'Washington Nationals': 'wsh',
}

const NFL_ABBRS = {
  'Arizona Cardinals': 'ari', 'Atlanta Falcons': 'atl', 'Baltimore Ravens': 'bal',
  'Buffalo Bills': 'buf', 'Carolina Panthers': 'car', 'Chicago Bears': 'chi',
  'Cincinnati Bengals': 'cin', 'Cleveland Browns': 'cle', 'Dallas Cowboys': 'dal',
  'Denver Broncos': 'den', 'Detroit Lions': 'det', 'Green Bay Packers': 'gb',
  'Houston Texans': 'hou', 'Indianapolis Colts': 'ind', 'Jacksonville Jaguars': 'jax',
  'Kansas City Chiefs': 'kc', 'Las Vegas Raiders': 'lv', 'Los Angeles Chargers': 'lac',
  'Los Angeles Rams': 'lar', 'Miami Dolphins': 'mia', 'Minnesota Vikings': 'min',
  'New England Patriots': 'ne', 'New Orleans Saints': 'no', 'New York Giants': 'nyg',
  'New York Jets': 'nyj', 'Philadelphia Eagles': 'phi', 'Pittsburgh Steelers': 'pit',
  'San Francisco 49ers': 'sf', 'Seattle Seahawks': 'sea', 'Tampa Bay Buccaneers': 'tb',
  'Tennessee Titans': 'ten', 'Washington Commanders': 'wsh',
}

const WNBA_ABBRS = {
  'Atlanta Dream': 'atl', 'Chicago Sky': 'chi', 'Connecticut Sun': 'conn',
  'Dallas Wings': 'dal', 'Golden State Valkyries': 'gs', 'Indiana Fever': 'ind',
  'Las Vegas Aces': 'lv', 'Los Angeles Sparks': 'la', 'Minnesota Lynx': 'min',
  'New York Liberty': 'ny', 'Phoenix Mercury': 'phx', 'Portland Fire': 'por',
  'Seattle Storm': 'sea', 'Toronto Tempo': 'tor', 'Washington Mystics': 'wsh',
}

// NCAA uses numeric ESPN team IDs (one id per school across CFB, MBB,
// WBB). Auto-generated from ESPN team endpoints — the map covers all
// D1 + most D2/D3 schools ESPN tracks, so a game between any covered
// schools renders logos in every sport that uses NCAA_IDS below.
const NCAA_IDS = {
  "Abilene Christian Wildcats": 2000,
  "Adams State Grizzlies": 2001,
  "Adrian Bulldogs": 2003,
  "Air Force Falcons": 2005,
  "Akron Zips": 2006,
  "Alabama A&M Bulldogs": 2010,
  "Alabama Crimson Tide": 333,
  "Alabama State Hornets": 2011,
  "Alabama State Lady Hornets": 2011,
  "Albany State Golden Rams": 2013,
  "Albion Britons": 2790,
  "Albright Lions": 2015,
  "Alcorn State Braves": 2016,
  "Alcorn State Lady Braves": 2016,
  "Alfred Saxons": 365,
  "Alfred State Pioneers": 3162,
  "Allegheny Gators": 2018,
  "Allen Yellow Jackets": 2019,
  "Alma Scots": 2800,
  "Alvernia Golden Wolves": 111674,
  "American International Yellow Jackets": 2022,
  "American University Eagles": 44,
  "Amherst Mammoths": 7,
  "Anderson (IN) Ravens": 2023,
  "Anderson (SC) Trojans": 129469,
  "Andrew Fighting Tigers": 134002,
  "Angelo State Rams": 2025,
  "App State Mountaineers": 2026,
  "Apprentice School Builders": 3111,
  "Arizona State Sun Devils": 9,
  "Arizona Wildcats": 12,
  "Arkansas Baptist Buffaloes": 124386,
  "Arkansas Monticello Boll Weevils": 2028,
  "Arkansas Razorbacks": 8,
  "Arkansas State Red Wolves": 2032,
  "Arkansas Tech Wonder Boys": 2033,
  "Arkansas-Pine Bluff Golden Lions": 2029,
  "Army Black Knights": 349,
  "Ashland Eagles": 308,
  "Assumption Greyhounds": 2038,
  "Auburn Tigers": 2,
  "Augsburg Auggies": 124,
  "Augustana (IL) Vikings": 2042,
  "Augustana (SD) Vikings": 2043,
  "Aurora Spartans": 2044,
  "Austin 'Roos": 2045,
  "Austin Peay Governors": 2046,
  "Ave Maria University Gyrenes": 3178,
  "Averett Cougars": 2047,
  "Avila University Eagles": 2048,
  "Azusa Pacific Cougars": 2049,
  "BLUEFIELD Ramblin' Rams": 495,
  "BYU Cougars": 252,
  "Baker University Baker": 488,
  "Baldwin Wallace Yellow Jackets": 188,
  "Ball State Cardinals": 2050,
  "Barton Bulldogs": 122666,
  "Bates Bobcats": 121,
  "Baylor Bears": 239,
  "Belhaven Blazers": 2056,
  "Bellarmine Knights": 91,
  "Belmont Bruins": 2057,
  "Beloit Buccaneers": 266,
  "Bemidji State Beavers": 132,
  "Benedict Tigers": 490,
  "Benedictine (IL) Eagles": 2283,
  "Benedictine College Ravens": 16111,
  "Bentley Falcons": 2060,
  "Berry Vikings": 2757,
  "Bethany (Ks)": 492,
  "Bethany (WV) Bison": 2062,
  "Bethel (MN) Royals": 2802,
  "Bethel University Tennessee Wildcats": 2064,
  "Bethune-Cookman Wildcats": 2065,
  "Binghamton Bearcats": 2066,
  "Black Hills State Yellow Jackets": 2069,
  "Bloomsburg Huskies": 2071,
  "Bluefield State Big Blue": 124180,
  "Bluffton Beavers": 2074,
  "Boise State Broncos": 68,
  "Boston College Eagles": 103,
  "Boston University Terriers": 104,
  "Bowdoin Polar Bears": 340,
  "Bowie State Bulldogs": 2075,
  "Bowling Green Falcons": 189,
  "Bradley Braves": 71,
  "Brevard Tornados": 2913,
  "Bridgewater Eagles": 2079,
  "Bridgewater State Bears": 18,
  "British Columbia British Col": 2080,
  "Brockport Golden Eagles": 2781,
  "Brown Bears": 225,
  "Bryant Bulldogs": 2803,
  "Bucknell Bison": 2083,
  "Buena Vista Beavers": 63,
  "Buffalo Bulls": 2084,
  "Buffalo State Bengals": 2085,
  "Butler Bulldogs": 2086,
  "CSU Pueblo ThunderWolves": 2570,
  "Cal Lutheran Kingsmen": 2094,
  "Cal Poly Mustangs": 13,
  "Cal State Bakersfield Roadrunners": 2934,
  "Cal State Fullerton Titans": 2239,
  "Cal State Northridge Matadors": 2463,
  "California (PA) Vulcans": 2858,
  "California Baptist Lancers": 2856,
  "California Golden Bears": 25,
  "Calvin Knights": 129738,
  "Campbell Fighting Camels": 2097,
  "Campbellsville University Tigers": 2098,
  "Canisius Golden Griffins": 2099,
  "Capital Comets": 424,
  "Carleton Knights": 2101,
  "Carnegie Mellon Tartans": 2102,
  "Carroll (WI) Pioneers": 32,
  "Carson Newman Eagles": 2105,
  "Carthage Firebirds": 2106,
  "Case Western Reserve Spartans": 2963,
  "Catawba Indians": 2107,
  "Catholic Cardinals": 2108,
  "Centenary (LA) Gentlemen": 101442,
  "Central Arkansas Bears": 2110,
  "Central College Dutch": 2964,
  "Central Connecticut Blue Devils": 2115,
  "Central Methodist Eagles": 2860,
  "Central Michigan Chippewas": 2117,
  "Central Missouri Mules": 2118,
  "Central Oklahoma Bronchos": 2122,
  "Central State Marauders": 2119,
  "Central Washington Wildcats": 2120,
  "Centre Colonels": 2121,
  "Chadron State Eagles": 2123,
  "Chapman Panthers": 411,
  "Charleston (WV) Golden Eagles": 2128,
  "Charleston Cougars": 232,
  "Charleston Southern Buccaneers": 2127,
  "Charlotte 49ers": 2429,
  "Charlotte Saints": 3253,
  "Chattanooga Mocs": 236,
  "Chicago Maroons": 80,
  "Chicago State Cougars": 2130,
  "Chowan Hawks": 2804,
  "Christopher Newport Captains": 3112,
  "Cincinnati Bearcats": 2132,
  "Claremont Mudd Scripps Stags": 17,
  "Clarion Golden Eagles": 2134,
  "Clark Atlanta Panthers": 2805,
  "Clemson Tigers": 228,
  "Cleveland State Vikings": 325,
  "Coast Guard Bears": 2557,
  "Coastal Carolina Chanticleers": 324,
  "Coe Kohawks": 2141,
  "Colby White Mules": 33,
  "Cole College Jaguars": 3210,
  "Colgate Raiders": 2142,
  "College of Idaho Yotes": 108382,
  "Colorado Buffaloes": 38,
  "Colorado Mesa Mavericks": 11,
  "Colorado School of Mines Orediggers": 2146,
  "Colorado State Rams": 36,
  "Columbia Lions": 171,
  "Concord Mountain Lions": 2148,
  "Concordia (MN) Cobbers": 2152,
  "Concordia (WI) Falcons": 409,
  "Concordia Chicago Cougars": 2151,
  "Concordia St. Paul Golden Bears": 3066,
  "Concordia University Nebraska Clippers": 507,
  "Concordia-Michigan Cardinals": 2985,
  "Coppin State Eagles": 2154,
  "Cornell (IA) Rams": 2155,
  "Cornell Big Red": 172,
  "Creighton Bluejays": 156,
  "Crown Polars": 509,
  "Culver-Stockton College Wildcats": 510,
  "Cumberland (TN) Bulldogs": 2161,
  "Cumberlands Indians": 511,
  "Curry Colonels": 40,
  "Dakota State University Trojans": 512,
  "Dakota Wesleyan Tigers": 513,
  "Dartmouth Big Green": 159,
  "Davidson Wildcats": 2166,
  "Dayton Flyers": 2168,
  "DePaul Blue Demons": 305,
  "DePauw Tigers": 83,
  "Dean Bulldogs": 110438,
  "Defiance College Yellow Jackets": 190,
  "Delaware Blue Hens": 48,
  "Delaware State Hornets": 2169,
  "Delaware Valley Aggies": 2808,
  "Delta State Statesmen": 2170,
  "Denison Big Red": 2171,
  "Denver Pioneers": 2172,
  "Des Moines Vikings": 2254,
  "Detroit Mercy Titans": 2174,
  "Dickinson Red Devils": 2175,
  "Dickinson State University Blue Hawks": 316,
  "Drake Bulldogs": 2181,
  "Drexel Dragons": 2182,
  "Dubuque Spartans": 49,
  "Duke Blue Devils": 150,
  "Duquesne Dukes": 2184,
  "East Carolina Pirates": 151,
  "East Central Tigers": 2191,
  "East Stroudsburg Warriors": 2188,
  "East Tennessee State Buccaneers": 2193,
  "East Tennessee State Bucs": 2193,
  "East Texas A&M Lions": 2837,
  "East Texas Baptist Tigers": 2194,
  "Eastern Eagles": 127954,
  "Eastern Illinois Panthers": 2197,
  "Eastern Kentucky Colonels": 2198,
  "Eastern Michigan Eagles": 2199,
  "Eastern New Mexico Greyhounds": 2201,
  "Eastern Oregon": 2202,
  "Eastern Washington Eagles": 331,
  "Edinboro Fighting Scots": 2205,
  "Edward Waters Tigers": 2206,
  "Elgin Eagles": 122775,
  "Elizabeth City State Vikings": 2207,
  "Elmhurst Bluejays": 72,
  "Elon Phoenix": 2210,
  "Emory & Henry Wasps": 2213,
  "Emporia State Hornets": 2214,
  "Endicott Gulls": 452,
  "Erskine Flying Fleet": 101784,
  "Eureka Red Devils": 101,
  "Evangel University Crusaders": 2865,
  "Evansville Purple Aces": 339,
  "FDU Florham Devils": 2221,
  "Fairfield Stags": 2217,
  "Fairleigh Dickinson Knights": 161,
  "Fairmont State Falcons": 2986,
  "Faulkner University Eagles": 2219,
  "Fayetteville State Broncos": 2220,
  "Ferris State Bulldogs": 2222,
  "Ferrum Panthers": 366,
  "Findlay Oilers": 2224,
  "Fitchburg State Falcons": 114,
  "Florida A&M Rattlers": 50,
  "Florida Atlantic Owls": 2226,
  "Florida Gators": 57,
  "Florida Gulf Coast Eagles": 526,
  "Florida International Panthers": 2229,
  "Florida Memorial University Lions": 125762,
  "Florida State Seminoles": 52,
  "Fordham Rams": 2230,
  "Fort Hays Tigers": 2231,
  "Fort Lewis Skyhawks": 2237,
  "Fort Valley State Wildcats": 2232,
  "Framingham State Rams": 2967,
  "Franklin & Marshall Diplomats": 2234,
  "Franklin Grizzlies": 2233,
  "Franklin Pierce Ravens": 112334,
  "Fresno State Bulldogs": 278,
  "Friends University Friends": 527,
  "Frostburg State Bobcats": 341,
  "Furman Paladins": 231,
  "Gallaudet Bison": 417,
  "Gannon Golden Knights": 367,
  "Gardner-Webb Runnin' Bulldogs": 2241,
  "Geneva Golden Tornadoes": 2242,
  "George Fox Bruins": 415,
  "George Mason Patriots": 2244,
  "George Mason University Patriots": 2244,
  "George Washington Revolutionaries": 45,
  "Georgetown College Kentucky Tigers": 2245,
  "Georgetown Hoyas": 46,
  "Georgia Bulldogs": 61,
  "Georgia Lady Bulldogs": 61,
  "Georgia Southern Eagles": 290,
  "Georgia State Panthers": 2247,
  "Georgia Tech Yellow Jackets": 59,
  "Gettysburg Bullets": 2248,
  "Glenville State Pioneers": 2249,
  "Gonzaga Bulldogs": 2250,
  "Graceland University Graceland": 530,
  "Grambling Lady Tigers": 2755,
  "Grambling Tigers": 2755,
  "Grand Canyon Lopes": 2253,
  "Grand Valley State Lakers": 125,
  "Green Bay Phoenix": 2739,
  "Greensboro Pride": 2256,
  "Greenville Panthers": 2257,
  "Grinnell Pioneers": 65,
  "Grove City Wolverines": 146,
  "Guilford Quakers": 2258,
  "Gustavus Adolphus Golden Gusties": 2968,
  "Hamilton Continentals": 348,
  "Hamline Pipers": 162,
  "Hampden Sydney Tigers": 297,
  "Hampton Lady Pirates": 2261,
  "Hampton Pirates": 2261,
  "Hanover Panthers": 2262,
  "Hardin Simmons Cowboys": 2810,
  "Harding Bisons": 2264,
  "Hartwick Hawks": 173,
  "Harvard Crimson": 108,
  "Haskell Indian Nations Univ Jayhawks": 535,
  "Hawai'i Rainbow Warriors": 62,
  "Heidelberg Student Princes": 191,
  "Henderson State Reddies": 2271,
  "Hendrix Warriors": 418,
  "High Point Panthers": 2272,
  "Hilbert Hawks": 125974,
  "Hillsdale Chargers": 2273,
  "Hiram Terriers": 2274,
  "Hobart Statesmen": 174,
  "Hofstra Pride": 2275,
  "Holland College Hurricanes": 108354,
  "Holy Cross Crusaders": 107,
  "Hope Flying Dutchmen": 2812,
  "Houston Christian Huskies": 2277,
  "Houston Cougars": 248,
  "Howard Bison": 47,
  "Howard Payne Yellow Jackets": 2758,
  "Huntingdon Hawks": 2938,
  "Husson Eagles": 2280,
  "IU Indianapolis Jaguars": 85,
  "IU Pennsylvania Crimson Hawks": 2291,
  "Idaho State Bengals": 304,
  "Idaho Vandals": 70,
  "Illinois College Blueboys": 2286,
  "Illinois Fighting Illini": 356,
  "Illinois State Redbirds": 2287,
  "Illinois Wesleyan Titans": 306,
  "Incarnate Word Cardinals": 2916,
  "Indiana Hoosiers": 84,
  "Indiana State Sycamores": 282,
  "Indiana Wesleyan Wildcats": 111756,
  "Indianapolis Greyhounds": 2292,
  "Iona Gaels": 314,
  "Iowa Hawkeyes": 2294,
  "Iowa State Cyclones": 66,
  "Ithaca Bombers": 175,
  "Jackson State Lady Tigers": 2296,
  "Jackson State Tigers": 2296,
  "Jacksonville Dolphins": 294,
  "Jacksonville State Gamecocks": 55,
  "James Madison Dukes": 256,
  "Jamestown Jimmies": 2939,
  "John Carroll Blue Streaks": 2302,
  "Johns Hopkins Blue Jays": 118,
  "Johnson C. Smith Golden Bulls": 2304,
  "Juniata Eagles": 246,
  "Kalamazoo Hornets": 126,
  "Kansas City Roos": 140,
  "Kansas Jayhawks": 2305,
  "Kansas State Wildcats": 2306,
  "Kansas Wesleyan Ks Wesleyan": 547,
  "Kean Cougars": 2871,
  "Keiser University Keiser": 126110,
  "Kennesaw State Owls": 338,
  "Kent State Golden Flashes": 2309,
  "Kentucky Christian Knights": 3077,
  "Kentucky State Thorobreds": 2310,
  "Kentucky Wesleyan Panthers": 2316,
  "Kentucky Wildcats": 96,
  "Kenyon Owls": 352,
  "Keystone Giants": 122774,
  "King's Monarchs": 247,
  "Knox Prairie Fire": 255,
  "Kutztown Golden Bears": 2315,
  "LSU New Orleans Privateers": 2443,
  "LSU Tigers": 99,
  "La Salle Explorers": 2325,
  "La Verne Leopards": 2318,
  "LaGrange Panthers": 548,
  "Lafayette Leopards": 322,
  "Lake Erie Storm": 437,
  "Lake Forest Foresters": 262,
  "Lakeland Muskies": 6353,
  "Lamar Cardinals": 2320,
  "Lane College Dragons": 2323,
  "Langston Lions": 2324,
  "Lawrence Vikings": 268,
  "Le Moyne Dolphins": 2330,
  "Lebanon Valley Flying Dutchmen": 388,
  "Lehigh Mountain Hawks": 2329,
  "Lenoir Rhyne Bears": 2331,
  "Lewis & Clark River Otters": 2333,
  "Liberty Flames": 2335,
  "Lincoln (CA) Oaklanders": 124179,
  "Lincoln (MO) Blue Tigers": 2876,
  "Lincoln (PA) Lions": 2339,
  "Lindenwood Belleville Lynx": 3209,
  "Lindenwood Lions": 2815,
  "Lindsey Wilson LINDSEY": 2877,
  "Linfield Wildcats": 203,
  "Lipscomb Bisons": 288,
  "Little Rock Trojans": 2031,
  "Livingstone Blue Bears": 2940,
  "Lock Haven Bald Eagles": 209,
  "Long Beach State Beach": 299,
  "Long Island University Sharks": 2341,
  "Longwood Lancers": 2344,
  "Loras Duhawks": 263,
  "Louisiana Christian Wildcats": 2347,
  "Louisiana Ragin' Cajuns": 309,
  "Louisiana Tech Bulldogs": 2348,
  "Louisiana Tech Lady Techsters": 2348,
  "Louisville Cardinals": 97,
  "Loyola Chicago Ramblers": 2350,
  "Loyola Maryland Greyhounds": 2352,
  "Loyola Marymount Lions": 2351,
  "Luther Norse": 67,
  "Lycoming Warriors": 2354,
  "Lyon Scots": 101161,
  "MADONNA": 126146,
  "MANITOBA": 2770,
  "MIT Engineers": 109,
  "Macalester Scots": 2359,
  "Maine Black Bears": 311,
  "Maine Maritime Mariners": 274,
  "Manchester Spartans": 2362,
  "Manhattan Jaspers": 2363,
  "Mansfield Mountaineers": 2365,
  "Marian (IN) MARIAN": 2366,
  "Marietta Pioneers": 317,
  "Marist Red Foxes": 2368,
  "Marquette Golden Eagles": 269,
  "Mars Hill Lions": 2369,
  "Marshall Thundering Herd": 276,
  "Martin Luther Knights": 446,
  "Mary Hardin Baylor Crusaders": 2371,
  "Maryland Eastern Shore Hawks": 2379,
  "Maryland Terrapins": 120,
  "Maryville (TN) Scots": 2373,
  "Mass Maritime Buccaneers": 110,
  "Massachusetts Minutemen": 113,
  "UMass Minutemen": 113,
  "UMass": 113,
  "Massachusetts Minutewomen": 113,
  "Mayville State Comets": 561,
  "McDaniel Green Terror": 2700,
  "McKendree Bearcats": 2816,
  "McMurry War Hawks": 241,
  "McNeese Cowboys": 2377,
  "McNeese Cowgirls": 2377,
  "Memphis Tigers": 235,
  "Mercer Bears": 2382,
  "Merchant Marine Mariners": 2383,
  "Mercyhurst Lakers": 2385,
  "Merrimack Warriors": 2771,
  "Methodist Monarchs": 291,
  "Miami (OH) RedHawks": 193,
  "Miami Hurricanes": 2390,
  "Michigan State Spartans": 127,
  "Michigan Tech Huskies": 2392,
  "Michigan Wolverines": 130,
  "Middle Tennessee Blue Raiders": 2393,
  "Middlebury Panthers": 2394,
  "Midland MIDLAND LUTHERAN": 565,
  "Midwestern State Mustangs": 2395,
  "Miles Golden Bears": 2396,
  "Millersville Marauders": 210,
  "Millikin Big Blue": 74,
  "Millsaps Majors": 2398,
  "Milwaukee Panthers": 270,
  "Minnesota Duluth Bulldogs": 134,
  "Minnesota Golden Gophers": 135,
  "Minnesota Morris Cougars": 2399,
  "Minnesota St Moorhead Dragons": 2817,
  "Minnesota State Mavericks": 2364,
  "Minot State Beavers": 568,
  "Misericordia Cougars": 2969,
  "Mississippi State Bulldogs": 344,
  "Mississippi Valley State Delta Devils": 2400,
  "Mississippi Valley State Devilettes": 2400,
  "Missouri Baptist Spartans": 2880,
  "Missouri S&T Miners": 2402,
  "Missouri Southern State Lions": 2403,
  "Missouri State Bears": 2623,
  "Missouri State Lady Bears": 2623,
  "Missouri Tigers": 142,
  "Missouri Western Griffons": 137,
  "Monmouth (IL) Fighting Scots": 2919,
  "Monmouth Hawks": 2405,
  "Monroe Mustangs": 134001,
  "Montana Grizzlies": 149,
  "Montana Lady Griz": 149,
  "Montana State Bobcats": 147,
  "Montana Western Bulldogs": 2701,
  "Montclair State Red Hawks": 2818,
  "Monterrey Tech Borregos": 3100,
  "Moravian Greyhounds": 323,
  "Morehead State Eagles": 2413,
  "Morehouse Maroon Tigers": 60,
  "Morgan State Bears": 2415,
  "Morgan State Lady Bears": 2415,
  "Morningside Chiefs": 2416,
  "Mount St Joseph Lions": 2419,
  "Mount St. Mary's Mountaineers": 116,
  "Mount Union Purple Raiders": 426,
  "Muhlenberg Mules": 2422,
  "Murray State Racers": 93,
  "Muskingum Fighting Muskies": 332,
  "NC State Wolfpack": 152,
  "NJIT Highlanders": 2885,
  "Navy Midshipmen": 2426,
  "Nebraska Cornhuskers": 158,
  "Nebraska Kearney Lopers": 2438,
  "Nebraska Wesleyan Prairie Wolves": 6845,
  "Nelson (TX) Lions": 2904,
  "Nevada Wolf Pack": 2440,
  "New England Nor'easters": 111675,
  "New Hampshire Wildcats": 160,
  "New Haven Chargers": 2441,
  "New Mexico Highlands Cowboys": 2424,
  "New Mexico Lobos": 167,
  "New Mexico State Aggies": 166,
  "Newberry Wolves": 2444,
  "Niagara Purple Eagles": 315,
  "Nicholls Colonels": 2447,
  "Nichols Bison": 2884,
  "Norfolk State Spartans": 2450,
  "North Alabama Lions": 2453,
  "North American Stallions": 123086,
  "North Carolina A&T Aggies": 2448,
  "North Carolina Central Eagles": 2428,
  "North Carolina Tar Heels": 153,
  "North Carolina Wesleyan Battling Bishops": 286,
  "North Central College Cardinals": 3071,
  "North Dakota Fighting Hawks": 155,
  "North Dakota State Bison": 2449,
  "North Florida Ospreys": 2454,
  "North Greenville Trailblazers": 2822,
  "North Park Vikings": 75,
  "North Texas Mean Green": 249,
  "Northeastern Huskies": 111,
  "Northeastern State RiverHawks": 196,
  "Northern Arizona Lumberjacks": 2464,
  "Northern Colorado Bears": 2458,
  "Northern Illinois Huskies": 2459,
  "Northern Iowa Panthers": 2460,
  "Northern Kentucky Norse": 94,
  "Northern Michigan Wildcats": 128,
  "Northern State Wolves": 425,
  "Northwest Missouri State Bearcats": 138,
  "Northwestern (MN) Eagles": 583,
  "Northwestern (OK) Rangers": 2823,
  "Northwestern State Demons": 2466,
  "Northwestern State Lady Demons": 2466,
  "Northwestern Wildcats": 77,
  "Northwood Timberwolves": 2886,
  "Norwich Cadets": 2467,
  "Notre Dame Fighting Irish": 87,
  "Oakland Golden Grizzlies": 2473,
  "Oberlin Yeomen": 391,
  "Ohio Bobcats": 195,
  "Ohio Northern Polar Bears": 427,
  "Ohio State Buckeyes": 194,
  "Ohio State Newark Titans": 3161,
  "Ohio Wesleyan Battling Bishops": 2980,
  "Oklahoma Baptist Bison": 319,
  "Oklahoma Panhandle OK PANHANDLE ST": 2824,
  "Oklahoma Sooners": 201,
  "Oklahoma State Cowboys": 197,
  "Oklahoma State Cowgirls": 197,
  "Old Dominion Monarchs": 295,
  "Ole Miss Rebels": 145,
  "Olivet Comets": 354,
  "Omaha Mavericks": 2437,
  "Oral Roberts Golden Eagles": 198,
  "Oregon Ducks": 2483,
  "Oregon State Beavers": 204,
  "Otterbein Cardinals": 359,
  "Ouachita Baptist Tigers": 2888,
  "Pace Setters": 2487,
  "Pacific (OR) Boxers": 205,
  "Pacific Lutheran Lutes": 2486,
  "Pacific Tigers": 279,
  "Penn State Lady Lions": 213,
  "Penn State Nittany Lions": 213,
  "Pennsylvania Quakers": 219,
  "Pepperdine Waves": 2492,
  "Phoenix Firestorm": 108358,
  "Pikeville Bears": 95,
  "Pittsburg State Gorillas": 90,
  "Pittsburgh Panthers": 221,
  "Plymouth State Panthers": 2972,
  "Point University Skyhawks": 3179,
  "Pomona Pitzer Sagehens": 2923,
  "Portland Pilots": 2501,
  "Portland State Vikings": 2502,
  "Post Eagles": 126086,
  "Prairie View A&M Lady Panthers": 2504,
  "Prairie View A&M Panthers": 2504,
  "Presbyterian Blue Hose": 2506,
  "Princeton Tigers": 163,
  "Providence Friars": 2507,
  "Puget Sound Loggers": 2508,
  "Purdue Boilermakers": 2509,
  "Purdue Fort Wayne Mastodons": 2870,
  "Queens University Royals": 2511,
  "Quincy Hawks": 2825,
  "Quinnipiac Bobcats": 2514,
  "Radford Highlanders": 2515,
  "Randolph Macon Yellow Jackets": 2516,
  "Redlands Bulldogs": 29,
  "Reinhardt Eagles": 2890,
  "Rensselaer Engineers": 2528,
  "Rhode Island Rams": 227,
  "Rhodes Lynx": 2519,
  "Rice Owls": 242,
  "Richmond Spiders": 257,
  "Rider Broncs": 2520,
  "Ripon Red Hawks": 2891,
  "Robert Morris Colonials": 2523,
  "Rochester (NY) Yellow Jackets": 184,
  "Rockford Regents": 2524,
  "Roosevelt Lakers": 599,
  "Rose Hulman Fightin' Engineers": 86,
  "Rowan Profs": 2827,
  "Rutgers Scarlet Knights": 164,
  "SE Louisiana Lady Lions": 2545,
  "SE Louisiana Lions": 2545,
  "SIU Edwardsville Cougars": 2565,
  "SMU Mustangs": 2567,
  "SUNY Cortland Red Dragons": 2782,
  "SUNY Erie Kats": 3236,
  "SUNY Maritime Privateers": 2951,
  "SUNY Morrisville Mustangs": 3110,
  "Sacramento State Hornets": 16,
  "Sacred Heart Pioneers": 2529,
  "Saginaw Valley State Cardinals": 129,
  "Saint Anselm Hawks": 2830,
  "Saint Francis (IN) Cougars": 2831,
  "Saint Francis Red Flash": 2598,
  "Saint John's (MN) Johnnies": 2600,
  "Saint Joseph's Hawks": 2603,
  "Saint Louis Billikens": 139,
  "Saint Mary's Gaels": 2608,
  "Saint Peter's Peacocks": 2612,
  "Saint Vincent Bearcats": 2614,
  "Saint Xavier Cougars": 2615,
  "Salisbury Sea Gulls": 2532,
  "Salve Regina Seahawks": 2776,
  "Sam Houston Bearkats": 2534,
  "Samford Bulldogs": 2535,
  "San Diego State Aztecs": 21,
  "San Diego Toreros": 301,
  "San Francisco Dons": 2539,
  "San José State Spartans": 23,
  "Santa Clara Broncos": 2541,
  "Savannah State Tigers": 2542,
  "Seattle U Redhawks": 2547,
  "Seton Hall Pirates": 2550,
  "Seton Hill Griffins": 611,
  "Sewanee Tigers": 2553,
  "Shaw Bears": 2551,
  "Shenandoah Hornets": 2828,
  "Shepherd Rams": 2974,
  "Shippensburg Raiders": 2559,
  "Shorter Hawks": 2560,
  "Siena Heights Saints": 2562,
  "Siena Saints": 2561,
  "Simpson (CA) Red Hawks": 129758,
  "Simpson (IA) Storm": 2564,
  "Sioux Falls Cougars": 2894,
  "Slippery Rock The Rock": 215,
  "South Alabama Jaguars": 6,
  "South Carolina Gamecocks": 2579,
  "South Carolina State Bulldogs": 2569,
  "South Carolina State Lady Bulldogs": 2569,
  "South Carolina Upstate Spartans": 2908,
  "South Dakota Coyotes": 233,
  "South Dakota Mines Hardrockers": 613,
  "South Dakota State Jackrabbits": 2571,
  "South Florida Bulls": 58,
  "Southeast Missouri State Redhawks": 2546,
  "Southeastern Fires": 267,
  "Southeastern Oklahoma State Savage Storm": 199,
  "Southern Arkansas Muleriders": 2568,
  "Southern Connecticut State Owls": 2583,
  "Southern Illinois Salukis": 79,
  "Southern Indiana Screaming Eagles": 88,
  "Southern Jaguars": 2582,
  "Southern Miss Golden Eagles": 2572,
  "Southern Miss Lady Eagles": 2572,
  "Southern Nazarene Crimson Storm": 200,
  "Southern Oregon Raiders": 2584,
  "Southern Utah Thunderbirds": 253,
  "Southern Virginia Knights": 2896,
  "Southwest Baptist Bearcats": 2586,
  "Southwest Minnesota State Mustangs": 2587,
  "Southwestern (KS) Moundbuilders": 616,
  "Southwestern Oklahoma State Bulldogs": 2927,
  "Southwestern U Pirates": 2588,
  "Springfield Pride": 81,
  "St. Ambrose Fighting Bees": 2591,
  "St. Andrews Knights": 111610,
  "St. Bonaventure Bonnies": 179,
  "St. Francis (IL) Fighting Saints": 2595,
  "St. John Fisher Cardinals": 374,
  "St. John's Red Storm": 2599,
  "St. Lawrence Saints": 2779,
  "St. Norbert Green Knights": 2832,
  "St. Olaf Oles": 133,
  "St. Petersburg Glory Eagles": 3254,
  "St. Scholastica Saints": 375,
  "St. Thomas Tommies": 2900,
  "Stanford Cardinal": 24,
  "Stephen F. Austin Ladyjacks": 2617,
  "Stephen F. Austin Lumberjacks": 2617,
  "Sterling STERLING KS": 618,
  "Stetson Hatters": 56,
  "Stevenson Mustangs": 471,
  "Stonehill Skyhawks": 284,
  "Stony Brook Seawolves": 2619,
  "Sul Ross State Lobos": 2834,
  "Susquehanna River Hawks": 216,
  "Syracuse Orange": 183,
  "TCU Horned Frogs": 2628,
  "Tarleton State Texans": 2627,
  "Taylor Trojans": 620,
  "Temple Owls": 218,
  "Tennessee Lady Volunteers": 2633,
  "Tennessee State Lady Tigers": 2634,
  "Tennessee State Tigers": 2634,
  "Tennessee Tech Golden Eagles": 2635,
  "Tennessee Volunteers": 2633,
  "Texas A&M Aggies": 245,
  "Texas A&M-Corpus Christi Islanders": 357,
  "Texas A&M-Kingsville Javelinas": 2658,
  "Texas College Steers": 2637,
  "Texas Longhorns": 251,
  "Texas Lutheran Bulldogs": 2639,
  "Texas Southern Tigers": 2640,
  "Texas State Bobcats": 326,
  "Texas Tech Lady Raiders": 2641,
  "Texas Tech Red Raiders": 2641,
  "The Citadel Bulldogs": 2643,
  "The College of New Jersey Lions": 2442,
  "Thiel Tomcats": 2644,
  "Thomas More Saints": 2646,
  "Thomas Night Hawks": 134000,
  "Tiffin Dragons": 2838,
  "Toledo Rockets": 2649,
  "Towson Tigers": 119,
  "Trine Thunder": 2651,
  "Trinity (CT) Bantams": 2977,
  "Trinity (TX) Tigers": 386,
  "Trinity Bible Lions": 3214,
  "Troy Trojans": 2653,
  "Troy Vikings": 3237,
  "Truman State Bulldogs": 2654,
  "Tufts Jumbos": 112,
  "Tulane Green Wave": 2655,
  "Tulsa Golden Hurricane": 202,
  "Tusculum Pioneers": 2839,
  "Tuskegee Golden Tigers": 2657,
  "UAB Blazers": 5,
  "UAlbany Great Danes": 399,
  "UC Davis Aggies": 302,
  "UC Irvine Anteaters": 300,
  "UC Riverside Highlanders": 27,
  "UC San Diego Tritons": 28,
  "UC Santa Barbara Gauchos": 2540,
  "UCF Knights": 2116,
  "UCLA Bruins": 26,
  "UConn Huskies": 41,
  "UIC Flames": 82,
  "UL Monroe Warhawks": 2433,
  "UMBC Retrievers": 2378,
  "UMass Dartmouth Corsairs": 379,
  "UMass Lowell River Hawks": 2349,
  "UNC Asheville Bulldogs": 2427,
  "UNC Greensboro Spartans": 2430,
  "UNC Pembroke Braves": 2882,
  "UNC Wilmington Seahawks": 350,
  "UNLV Lady Rebels": 2439,
  "UNLV Rebels": 2439,
  "USC Trojans": 30,
  "UT Arlington Mavericks": 250,
  "UT Martin Skyhawks": 2630,
  "UT Permian Basin Falcons": 110243,
  "UT Rio Grande Valley Vaqueros": 292,
  "UTEP Miners": 2638,
  "UTSA Roadrunners": 2636,
  "UVA Wise Cavaliers": 2842,
  "Union Garnet Chargers": 237,
  "University of Mary Marauders": 559,
  "University of Mexico MEXICO U": 3212,
  "Upper Iowa Peacocks": 389,
  "Ursinus Bears": 2667,
  "Utah State Aggies": 328,
  "Utah Tech Trailblazers": 3101,
  "Utah Utes": 254,
  "Utah Valley Wolverines": 3084,
  "Utica Pioneers": 390,
  "VCU Rams": 2670,
  "VMI Keydets": 2678,
  "Valdosta State Blazers": 2673,
  "Valley City State VALLEY CITY ST": 628,
  "Valparaiso Beacons": 2674,
  "Vanderbilt Commodores": 238,
  "Vermont Catamounts": 261,
  "Vermont State Castleton Spartans": 293,
  "Villanova Wildcats": 222,
  "Virginia Cavaliers": 258,
  "Virginia Lynchburg Dragons": 2355,
  "Virginia State Trojans": 330,
  "Virginia Tech Hokies": 259,
  "Virginia Union Panthers": 2676,
  "WPI Engineers": 2749,
  "WVU Tech Golden Bears": 2706,
  "Wabash Little Giants": 89,
  "Wagner Seahawks": 2681,
  "Wake Forest Demon Deacons": 154,
  "Waldorf Warriors": 3080,
  "Walsh Cavaliers": 2682,
  "Warner Royals": 2683,
  "Wartburg Knights": 2685,
  "Washburn Ichabods": 2687,
  "Washington & Jefferson Presidents": 2686,
  "Washington Huskies": 264,
  "Washington St. Louis Bears": 143,
  "Washington State Cougars": 265,
  "Washington and Lee Generals": 2688,
  "Wayland Baptist Pioneers": 630,
  "Wayne State (MI) Warriors": 131,
  "Wayne State (NE) Wildcats": 2844,
  "Waynesburg Yellow Jackets": 2845,
  "Webber International Warriors": 2691,
  "Weber State Wildcats": 2692,
  "Wesleyan (CT) Cardinals": 336,
  "West Alabama Tigers": 2695,
  "West Chester Golden Rams": 223,
  "West Florida Argonauts": 110242,
  "West Georgia Wolves": 2698,
  "West Liberty Hilltoppers": 2699,
  "West Memphis Crusaders": 3211,
  "West Texas Buffaloes": 2704,
  "West Virginia Mountaineers": 277,
  "West Virginia State Yellow Jackets": 2707,
  "West Virginia Wesleyan Bobcats": 455,
  "Western Carolina Catamounts": 2717,
  "Western Colorado Mountaineers": 2714,
  "Western Connecticut State Wolves": 2843,
  "Western Illinois Leathernecks": 2710,
  "Western Kentucky Hilltoppers": 98,
  "Western Kentucky Lady Toppers": 98,
  "Western Michigan Broncos": 2711,
  "Western New England Golden Bears": 2702,
  "Western New Mexico Mustangs": 2703,
  "Western Oregon Wolves": 2848,
  "Westfield State Owls": 2909,
  "Westgate Christian University Ravens": 134087,
  "Westminster (MO) Blue Jays": 433,
  "Westminster (PA) Titans": 2849,
  "Wheaton (IL) Thunder": 396,
  "Wheeling Cardinals": 112335,
  "Whittier Poets": 2850,
  "Whitworth Pirates": 2721,
  "Wichita State Shockers": 2724,
  "Widener Pride": 2725,
  "Wilkes Colonels": 398,
  "Willamette Bearcats": 2930,
  "William & Mary Tribe": 2729,
  "William Jewell Cardinals": 2911,
  "William Paterson Pioneers": 2970,
  "William Penn Statesmen": 2912,
  "Williams Ephs": 2731,
  "Williamson Mechanics": 3130,
  "Wilmington (OH) Fightin' Quakers": 2733,
  "Wingate Bulldogs": 351,
  "Winona State Warriors": 2851,
  "Winston-Salem State Rams": 2736,
  "Winthrop Eagles": 2737,
  "Wisconsin Badgers": 275,
  "Wisconsin Eau Claire Blugolds": 2738,
  "Wisconsin La Crosse Eagles": 2740,
  "Wisconsin Lutheran Warriors": 2741,
  "Wisconsin Oshkosh Titans": 271,
  "Wisconsin Platteville Pioneers": 272,
  "Wisconsin River Falls Falcons": 2723,
  "Wisconsin Stevens Point Pointers": 2743,
  "Wisconsin Stout Blue Devils": 2744,
  "Wisconsin Whitewater Warhawks": 2745,
  "Wittenberg Tigers": 2746,
  "Wofford Terriers": 2747,
  "Wooster Fighting Scots": 2748,
  "Worcester State Lancers": 402,
  "Wright State Raiders": 2750,
  "Wyoming Cowboys": 2751,
  "Wyoming Cowgirls": 2751,
  "Xavier Musketeers": 2752,
  "Yale Bulldogs": 43,
  "Youngstown State Penguins": 2754,
}

const UFL_ABBRS = {
  'Birmingham Stallions': 'bham', 'Columbus Aviators': 'clb',
  'DC Defenders': 'dc', 'DC DEFENDERS': 'dc',
  'Dallas Renegades': 'dal', 'Houston Gamblers': 'hou',
  'Louisville Kings': 'lou', 'Orlando Storm': 'orl',
  'St. Louis Battlehawks': 'stl', 'St Louis Battlehawks': 'stl',
}

// MLS team → ESPN numeric ID (same pattern as NCAA). Includes name
// variants for teams whose odds-API/DB name differs from ESPN's
// display name (Red Bull New York vs New York Red Bulls, unaccented
// Montreal, unofficial St Louis casing).
const MLS_IDS = {
  'Atlanta United FC': '18418', 'Atlanta United': '18418',
  'Austin FC': '20906',
  'CF Montréal': '9720', 'CF Montreal': '9720',
  'Charlotte FC': '21300',
  'Chicago Fire FC': '182', 'Chicago Fire': '182',
  'Colorado Rapids': '184',
  'Columbus Crew': '183',
  'Columbus Crew SC': '183',
  'D.C. United': '193', 'DC United': '193',
  'FC Cincinnati': '18267',
  'FC Dallas': '185',
  'Houston Dynamo FC': '6077', 'Houston Dynamo': '6077',
  'Inter Miami CF': '20232', 'Inter Miami': '20232',
  'LA Galaxy': '187',
  'LAFC': '18966', 'Los Angeles FC': '18966',
  'Minnesota United FC': '17362', 'Minnesota United': '17362',
  'Nashville SC': '18986',
  'New England Revolution': '189',
  'New York City FC': '17606', 'NYC FC': '17606', 'NYCFC': '17606',
  'Orlando City SC': '12011', 'Orlando City': '12011',
  'Philadelphia Union': '10739',
  'Portland Timbers': '9723',
  'Real Salt Lake': '4771',
  'Red Bull New York': '190', 'New York Red Bulls': '190',
  'San Diego FC': '22529',
  'San Jose Earthquakes': '191',
  'Seattle Sounders FC': '9726', 'Seattle Sounders': '9726',
  'Sporting Kansas City': '186', 'Sporting KC': '186',
  'St. Louis CITY SC': '21812', 'St. Louis City SC': '21812', 'St Louis City SC': '21812',
  'Toronto FC': '7318',
  'Vancouver Whitecaps': '9727', 'Vancouver Whitecaps FC': '9727',
}

const SPORT_MAP = {
  icehockey_nhl: { abbrs: NHL_ABBRS, sport: 'nhl' },
  basketball_nba: { abbrs: NBA_ABBRS, sport: 'nba' },
  baseball_mlb: { abbrs: MLB_ABBRS, sport: 'mlb' },
  americanfootball_nfl: { abbrs: NFL_ABBRS, sport: 'nfl' },
  // Preseason NFL games use the same team abbreviations as the regular
  // season — Panthers are Panthers either way — so we reuse NFL_ABBRS.
  // Without this entry, preseason game cards would silently render
  // without logos even though every other NFL/WNBA/MLB/NBA card has them.
  americanfootball_nfl_preseason: { abbrs: NFL_ABBRS, sport: 'nfl' },
  basketball_wnba: { abbrs: WNBA_ABBRS, sport: 'wnba' },
  americanfootball_ufl: { abbrs: UFL_ABBRS, sport: 'ufl' },
  americanfootball_ncaaf: { ids: NCAA_IDS, sport: 'ncaa' },
  basketball_ncaab: { ids: NCAA_IDS, sport: 'ncaa' },
  basketball_wncaab: { ids: NCAA_IDS, sport: 'ncaa' },
  // MLS uses ESPN numeric team IDs, under the `soccer` sport folder.
  soccer_usa_mls: { ids: MLS_IDS, sport: 'soccer' },
}

// Canonical 3-letter team abbreviations for display (e.g. prop card
// headers). Distinct from the logo-URL slugs above because ESPN's logo
// CDN uses shorter codes (gs, ny, no, sa, la, sj, tb) than the standard
// sports-broadcast abbreviations (GSW, NYK, NOP, SAS, LAK, SJS, TBL).
// Names are unique strings across sports so no sport key is needed.
const CANONICAL_ABBRS = {
  // NBA
  'Atlanta Hawks': 'ATL', 'Boston Celtics': 'BOS', 'Brooklyn Nets': 'BKN',
  'Charlotte Hornets': 'CHA', 'Chicago Bulls': 'CHI', 'Cleveland Cavaliers': 'CLE',
  'Dallas Mavericks': 'DAL', 'Denver Nuggets': 'DEN', 'Detroit Pistons': 'DET',
  'Golden State Warriors': 'GSW', 'Houston Rockets': 'HOU', 'Indiana Pacers': 'IND',
  'LA Clippers': 'LAC', 'Los Angeles Clippers': 'LAC', 'Los Angeles Lakers': 'LAL',
  'LA Lakers': 'LAL', 'Memphis Grizzlies': 'MEM', 'Miami Heat': 'MIA',
  'Milwaukee Bucks': 'MIL', 'Minnesota Timberwolves': 'MIN', 'New Orleans Pelicans': 'NOP',
  'New York Knicks': 'NYK', 'Oklahoma City Thunder': 'OKC', 'Orlando Magic': 'ORL',
  'Philadelphia 76ers': 'PHI', 'Phoenix Suns': 'PHX', 'Portland Trail Blazers': 'POR',
  'Sacramento Kings': 'SAC', 'San Antonio Spurs': 'SAS', 'Toronto Raptors': 'TOR',
  'Utah Jazz': 'UTA', 'Washington Wizards': 'WAS',
  // NHL
  'Anaheim Ducks': 'ANA', 'Arizona Coyotes': 'ARI', 'Boston Bruins': 'BOS',
  'Buffalo Sabres': 'BUF', 'Calgary Flames': 'CGY', 'Carolina Hurricanes': 'CAR',
  'Chicago Blackhawks': 'CHI', 'Colorado Avalanche': 'COL', 'Columbus Blue Jackets': 'CBJ',
  'Dallas Stars': 'DAL', 'Detroit Red Wings': 'DET', 'Edmonton Oilers': 'EDM',
  'Florida Panthers': 'FLA', 'Los Angeles Kings': 'LAK', 'Minnesota Wild': 'MIN',
  'Montreal Canadiens': 'MTL', 'Montréal Canadiens': 'MTL',
  'Nashville Predators': 'NSH', 'New Jersey Devils': 'NJD',
  'New York Islanders': 'NYI', 'New York Rangers': 'NYR', 'Ottawa Senators': 'OTT',
  'Philadelphia Flyers': 'PHI', 'Pittsburgh Penguins': 'PIT', 'San Jose Sharks': 'SJS',
  'Seattle Kraken': 'SEA', 'St. Louis Blues': 'STL', 'St Louis Blues': 'STL',
  'Tampa Bay Lightning': 'TBL', 'Toronto Maple Leafs': 'TOR',
  'Utah Hockey Club': 'UTA', 'Utah Mammoth': 'UTA',
  'Vancouver Canucks': 'VAN', 'Vegas Golden Knights': 'VGK', 'Washington Capitals': 'WSH',
  'Winnipeg Jets': 'WPG',
  // MLB
  'Arizona Diamondbacks': 'ARI', 'Atlanta Braves': 'ATL', 'Baltimore Orioles': 'BAL',
  'Boston Red Sox': 'BOS', 'Chicago Cubs': 'CHC', 'Chicago White Sox': 'CHW',
  'Cincinnati Reds': 'CIN', 'Cleveland Guardians': 'CLE', 'Colorado Rockies': 'COL',
  'Detroit Tigers': 'DET', 'Houston Astros': 'HOU', 'Kansas City Royals': 'KC',
  'Los Angeles Angels': 'LAA', 'Los Angeles Dodgers': 'LAD', 'Miami Marlins': 'MIA',
  'Milwaukee Brewers': 'MIL', 'Minnesota Twins': 'MIN', 'New York Mets': 'NYM',
  'New York Yankees': 'NYY', 'Oakland Athletics': 'ATH', 'Athletics': 'ATH',
  'Philadelphia Phillies': 'PHI', 'Pittsburgh Pirates': 'PIT', 'San Diego Padres': 'SD',
  'San Francisco Giants': 'SF', 'Seattle Mariners': 'SEA',
  'St. Louis Cardinals': 'STL', 'St Louis Cardinals': 'STL',
  'Tampa Bay Rays': 'TB', 'Texas Rangers': 'TEX', 'Toronto Blue Jays': 'TOR',
  'Washington Nationals': 'WSH',
  // NFL
  'Arizona Cardinals': 'ARI', 'Atlanta Falcons': 'ATL', 'Baltimore Ravens': 'BAL',
  'Buffalo Bills': 'BUF', 'Carolina Panthers': 'CAR', 'Chicago Bears': 'CHI',
  'Cincinnati Bengals': 'CIN', 'Cleveland Browns': 'CLE', 'Dallas Cowboys': 'DAL',
  'Denver Broncos': 'DEN', 'Detroit Lions': 'DET', 'Green Bay Packers': 'GB',
  'Houston Texans': 'HOU', 'Indianapolis Colts': 'IND', 'Jacksonville Jaguars': 'JAX',
  'Kansas City Chiefs': 'KC', 'Las Vegas Raiders': 'LV', 'Los Angeles Chargers': 'LAC',
  'Los Angeles Rams': 'LAR', 'Miami Dolphins': 'MIA', 'Minnesota Vikings': 'MIN',
  'New England Patriots': 'NE', 'New Orleans Saints': 'NO', 'New York Giants': 'NYG',
  'New York Jets': 'NYJ', 'Philadelphia Eagles': 'PHI', 'Pittsburgh Steelers': 'PIT',
  'San Francisco 49ers': 'SF', 'Seattle Seahawks': 'SEA', 'Tampa Bay Buccaneers': 'TB',
  'Tennessee Titans': 'TEN', 'Washington Commanders': 'WSH',
  // WNBA
  'Atlanta Dream': 'ATL', 'Chicago Sky': 'CHI', 'Connecticut Sun': 'CONN',
  'Dallas Wings': 'DAL', 'Golden State Valkyries': 'GSV', 'Indiana Fever': 'IND',
  'Las Vegas Aces': 'LV', 'Los Angeles Sparks': 'LA', 'Minnesota Lynx': 'MIN',
  'New York Liberty': 'NY', 'Phoenix Mercury': 'PHX', 'Portland Fire': 'POR',
  'Seattle Storm': 'SEA', 'Toronto Tempo': 'TOR', 'Washington Mystics': 'WAS',
  // UFL
  'Birmingham Stallions': 'BHM', 'Columbus Aviators': 'CLB',
  'DC Defenders': 'DC', 'DC DEFENDERS': 'DC',
  'Dallas Renegades': 'DAL', 'Houston Gamblers': 'HOU',
  'Louisville Kings': 'LOU', 'Orlando Storm': 'ORL',
  'St. Louis Battlehawks': 'STL', 'St Louis Battlehawks': 'STL',
}

// Normalize team names to a form that matches across sources:
// strip diacritics ("San José" → "San Jose"), fold curly quotes /
// ʻokina to straight ("Hawai'i" → "hawai'i" → "hawaii"), collapse
// whitespace, lowercase. Odds sources spell "San Jose State" while
// ESPN spells "San José State" — this bridges the two.
function normalizeName(s) {
  if (!s) return ''
  return s
    .normalize('NFD').replace(/[̀-ͯ]/g, '')
    .replace(/[ʻʼ‘’]/g, "'")
    .replace(/'/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase()
}

// Lazy per-map cache of { normalizedKey -> originalValue } so a
// normalize-fallback lookup doesn't rebuild the reverse map every call.
const _normCache = new WeakMap()
function normalizedLookup(map, teamName) {
  if (!map || !teamName) return null
  const direct = map[teamName]
  if (direct != null) return direct
  let cached = _normCache.get(map)
  if (!cached) {
    cached = {}
    for (const k of Object.keys(map)) cached[normalizeName(k)] = map[k]
    _normCache.set(map, cached)
  }
  return cached[normalizeName(teamName)] ?? null
}

export function getTeamAbbr(teamName) {
  if (!teamName) return ''
  return normalizedLookup(CANONICAL_ABBRS, teamName) || null
}

export function getTeamLogoUrl(teamName, sportKey) {
  // World Cup teams are countries — ESPN serves flags from a separate path
  // (i/teamlogos/countries/...) and there's no "dark" variant. Delegate to the
  // country-flag resolver so we don't end up looking for esp.png under nba/.
  if (sportKey === 'soccer_world_cup') {
    return getCountryFlagUrl(teamName)
  }
  const config = SPORT_MAP[sportKey]
  if (!config) return null
  // ESPN's "-dark" means "variant FOR dark backgrounds" — it's the LIGHT
  // artwork, which is what we want on our near-black UI. NCAA used to be
  // excluded here on the belief that -dark was the dark-on-transparent one;
  // measuring the actual images shows the opposite. Across an 18-team NCAA
  // sample, -dark was brighter for 14, identical for 4, and worse for none.
  // On the standard variant Iowa and Wake Forest average luminance 0 — they
  // render as literally invisible blobs. Ohio State sits at 52 with 45% of
  // its pixels near-black, which is what surfaced this.
  // getTeamLogoFallbackUrl still points at /500/ for the rare team with no
  // -dark artwork.
  const variant = '500-dark'
  if (config.ids) {
    const id = normalizedLookup(config.ids, teamName)
    if (!id) return null
    return `https://a.espncdn.com/i/teamlogos/${config.sport}/${variant}/${id}.png`
  }
  const abbr = normalizedLookup(config.abbrs, teamName)
  if (!abbr) return null
  return `https://a.espncdn.com/i/teamlogos/${config.sport}/${variant}/${abbr}.png`
}

// Standard (non-dark) URL as fallback
export function getTeamLogoFallbackUrl(teamName, sportKey) {
  if (sportKey === 'soccer_world_cup') {
    // Countries already use the standard (non-dark) URL — no fallback variant.
    return null
  }
  const config = SPORT_MAP[sportKey]
  if (!config) return null
  if (config.ids) {
    const id = normalizedLookup(config.ids, teamName)
    if (!id) return null
    return `https://a.espncdn.com/i/teamlogos/${config.sport}/500/${id}.png`
  }
  const abbr = normalizedLookup(config.abbrs, teamName)
  if (!abbr) return null
  return `https://a.espncdn.com/i/teamlogos/${config.sport}/500/${abbr}.png`
}
