const ONBOARDING_STEPS = [
  {
    page: null,
    targetSelector: null,
    title: 'Welcome to I KNOW BALL',
    body: "Let's take a quick tour so you can start making picks and climbing the leaderboard.",
    position: 'center',
    buttonText: "Let's Go",
  },
  {
    page: '/settings',
    targetSelector: null,
    title: 'Set Up Your Profile',
    body: "Add a display name, avatar, and bio to make your profile yours. You can also link your socials — X, Instagram, and more — so other ballers can find and follow you on other platforms too.",
    position: 'center',
    freeScroll: true,
  },
  {
    page: '/picks',
    targetSelector: '[data-onboarding="game-card"]',
    title: 'Pick Your Winners',
    body: 'Tap a team to pick them. You risk points (red) on every pick — get it right and you win the reward (green). Higher odds = bigger reward.',
    position: 'top',
    freeScroll: true,
  },
  {
    page: '/picks',
    targetSelector: '[data-onboarding="parlay-toggle"]',
    title: 'Build Parlays',
    body: 'Switch to Parlay mode to combine multiple picks into one. Hit them all for a bigger reward — miss one and you lose it all.',
    position: 'bottom',
    borderRadius: 8,
    padding: 4,
  },
  {
    page: '/',
    targetSelector: '[data-onboarding="featured-prop"]',
    title: 'Player Props',
    body: "Pick on individual player performances — like points, rebounds, or touchdowns. There's a new featured prop every day. You can find it here on the home page or under its sport on the Picks page.",
    position: 'top',
    freeScroll: true,
  },
  {
    page: '/leaderboard',
    targetSelector: null,
    title: 'Climb the Leaderboard',
    body: 'Earn points from your picks to climb tiers — from Rookie all the way to GOAT. See how you stack up against everyone.',
    position: 'center',
    freeScroll: true,
  },
  {
    page: '/leagues',
    targetSelector: '[data-onboarding="leagues-actions"]',
    title: 'Compete in Leagues',
    body: "Create or join leagues to compete with friends. Play Pick'em, Survivor, Squares, or Brackets formats across different sports.",
    position: 'bottom',
  },
  {
    page: '/hall-of-fame',
    targetSelector: null,
    title: 'Hall of Fame',
    body: 'See who holds the crown, check out all-time records, and read the weekly headlines recap. Scroll around and explore!',
    position: 'center',
    freeScroll: true,
  },
  {
    page: '/hub',
    targetSelector: null,
    title: 'Your Hub',
    body: "This is your home base. View your profile, manage your connections, and see recent highlights from the people you follow.",
    position: 'center',
    freeScroll: true,
  },
  {
    page: null,
    targetSelector: '[data-onboarding="hamburger-menu"]',
    title: 'Explore the Menu',
    body: 'Access your settings, FAQ, Hall of Fame, and more from the menu. You can also switch between accounts here.',
    position: 'bottom',
  },
  {
    page: null,
    targetSelector: null,
    title: "You're All Set",
    body: "You've got everything you need to start making picks. Good luck — show 'em you know ball.",
    position: 'center',
    buttonText: "Let's Go",
  },
]

export default ONBOARDING_STEPS
