const ONBOARDING_STEPS = [
  {
    page: null,
    targetSelector: null,
    title: 'Welcome to I KNOW BALL',
    body: "The fantasy sports platform where you make picks, compete in leagues, and climb the leaderboard across every major sport. Keep in mind — you can replay this tutorial anytime from the FAQ page.",
    position: 'center',
    buttonText: "Let's Go",
  },
  {
    page: '/picks',
    targetSelector: '[data-onboarding="game-card"]',
    title: 'Make Your Picks',
    body: "There are three ways to make picks. Straight picks — tap a team to pick the winner. Parlays — combine multiple picks for a bigger payout (miss one and you lose it all). Player props — pick on individual performances like points, rebounds, or strikeouts. You can pick across any sport — NBA, MLB, NFL, NHL, and more.",
    position: 'top',
    freeScroll: true,
  },
  {
    page: '/?headlines=1',
    targetSelector: null,
    title: 'Your Home Page',
    body: "This is your landing page. New featured props are refreshed daily. Tap game statuses for live scores and details. Browse the weekly headlines recap, and discover featured open leagues you can join right from here.",
    position: 'center',
    freeScroll: true,
  },
  {
    page: '/leagues/join',
    targetSelector: null,
    title: 'Join Open Leagues',
    body: "Browse leagues created by other users and jump right in. Leagues span different sports and formats — find one that fits your style and start competing.",
    position: 'center',
    freeScroll: true,
  },
  {
    page: '/leagues/create',
    targetSelector: null,
    title: 'Create Leagues',
    body: "Commissioners love this app. Create Fantasy Football, Daily Fantasy (NBA & MLB), Survivor Pools, Brackets, Pick'em, Squares, and more. Customize everything — scoring, duration, visibility — and invite your friends.",
    position: 'center',
    freeScroll: true,
  },
  {
    page: '/leaderboard',
    targetSelector: null,
    title: 'Climb the Leaderboard',
    body: 'Earn points from your picks and league finishes to climb tiers — from Rookie all the way to GOAT. There\u2019s an overall leaderboard and a leaderboard for every sport, so you can see who really knows ball.',
    position: 'center',
    freeScroll: true,
  },
  {
    page: '/hall-of-fame',
    targetSelector: null,
    title: 'Hall of Fame & Record Book',
    body: "The record book, weekly headlines, and hot takes all live here. See who holds the crown, check out all-time records, and drop your own hot takes.",
    position: 'center',
    freeScroll: true,
  },
  {
    page: '/hub?tab=all',
    targetSelector: null,
    title: 'Your Hub',
    body: "Your home base. View your profile, manage your connections, and browse the activity feed. Create posts, predictions, and polls to share with your squad. \"All of IKB\" shows what everyone across the platform is up to, plus a live ESPN news feed to stay on top of what\u2019s happening in sports.",
    position: 'center',
    freeScroll: true,
  },
  {
    page: null,
    targetSelector: '[data-onboarding="hamburger-menu"]',
    title: 'The Menu',
    body: 'This is where you\u2019ll find the Hall of Fame & Record Book, FAQ, Share IKB with friends, account switching, and settings.',
    position: 'bottom',
  },
  {
    page: null,
    targetSelector: null,
    title: "You're All Set",
    body: "Make picks across every sport, compete in fantasy football leagues, survivor pools, daily fantasy, squares, brackets, and so much more. Good luck — show 'em you know ball.",
    position: 'center',
    buttonText: "Let's Go",
  },
]

export default ONBOARDING_STEPS
