ALTER TABLE games
  ADD COLUMN IF NOT EXISTS period TEXT,
  ADD COLUMN IF NOT EXISTS clock TEXT,
  ADD COLUMN IF NOT EXISTS live_home_score INTEGER,
  ADD COLUMN IF NOT EXISTS live_away_score INTEGER;
