-- Remove old generic NFL backdrop
DELETE FROM league_backdrops WHERE filename = 'nfl-fantasy-1.webp';

INSERT INTO league_backdrops (filename, label, formats) VALUES
  ('nfl-acrisure.webp', 'Acrisure Stadium', '{football_nfl}'),
  ('nfl-allegiant.webp', 'Allegiant Stadium', '{football_nfl}'),
  ('nfl-arrowhead.webp', 'Arrowhead Stadium', '{football_nfl}'),
  ('nfl-atandt.webp', 'AT&T Stadium', '{football_nfl}'),
  ('nfl-b-of-a.webp', 'Bank of America Stadium', '{football_nfl}'),
  ('nfl-backyard-ball.webp', 'Backyard Ball', '{football_nfl}'),
  ('nfl-everbank.webp', 'EverBank Stadium', '{football_nfl}'),
  ('nfl-ford.webp', 'Ford Field', '{football_nfl}'),
  ('nfl-gillette.webp', 'Gillette Stadium', '{football_nfl}'),
  ('nfl-hard-rock.webp', 'Hard Rock Stadium', '{football_nfl}'),
  ('nfl-highmark.webp', 'Highmark Stadium', '{football_nfl}'),
  ('nfl-huntington-bank.webp', 'Huntington Bank Field', '{football_nfl}'),
  ('nfl-illuminate.webp', 'Illuminate Field', '{football_nfl}'),
  ('nfl-lambeau.webp', 'Lambeau Field', '{football_nfl}'),
  ('nfl-levis.webp', 'Levi''s Stadium', '{football_nfl}'),
  ('nfl-lincoln-financial.webp', 'Lincoln Financial Field', '{football_nfl}'),
  ('nfl-lucas-oil.webp', 'Lucas Oil Stadium', '{football_nfl}'),
  ('nfl-lumen-field.webp', 'Lumen Field', '{football_nfl}'),
  ('nfl-mandt-bank.webp', 'M&T Bank Stadium', '{football_nfl}'),
  ('nfl-mercedes-benz.webp', 'Mercedes-Benz Stadium', '{football_nfl}'),
  ('nfl-metlife-blue.webp', 'MetLife Stadium (Giants)', '{football_nfl}'),
  ('nfl-metlife-green.webp', 'MetLife Stadium (Jets)', '{football_nfl}'),
  ('nfl-mile-high.webp', 'Empower Field at Mile High', '{football_nfl}'),
  ('nfl-nissan.webp', 'Nissan Stadium', '{football_nfl}'),
  ('nfl-northwest.webp', 'Northwest Stadium', '{football_nfl}'),
  ('nfl-nrg.webp', 'NRG Stadium', '{football_nfl}'),
  ('nfl-packers-giants-1930.webp', 'Packers vs Giants 1930', '{football_nfl}'),
  ('nfl-paycor.webp', 'Paycor Stadium', '{football_nfl}'),
  ('nfl-rams-browns-1955.webp', 'Rams vs Browns 1955', '{football_nfl}'),
  ('nfl-raymond-james.webp', 'Raymond James Stadium', '{football_nfl}'),
  ('nfl-sofi-blue.webp', 'SoFi Stadium (Rams)', '{football_nfl}'),
  ('nfl-sofi-bolt.webp', 'SoFi Stadium (Chargers)', '{football_nfl}'),
  ('nfl-sofi.webp', 'SoFi Stadium', '{football_nfl}'),
  ('nfl-soldier.webp', 'Soldier Field', '{football_nfl}'),
  ('nfl-state-farm.webp', 'State Farm Stadium', '{football_nfl}'),
  ('nfl-super-bowl-1.webp', 'Super Bowl I', '{football_nfl}'),
  ('nfl-superdome.webp', 'Caesars Superdome', '{football_nfl}'),
  ('nfl-us-bank.webp', 'U.S. Bank Stadium', '{football_nfl}')
ON CONFLICT (filename) DO NOTHING;
