INSERT INTO league_backdrops (filename, label, formats) VALUES
  ('nba-american-airlines.webp', 'American Airlines Center', '{basketball_nba}'),
  ('nba-ball.webp', 'Ball Arena', '{basketball_nba}'),
  ('nba-barclays.webp', 'Barclays Center', '{basketball_nba}'),
  ('nba-buzz-city.webp', 'Buzz City', '{basketball_nba}'),
  ('nba-capital-one.webp', 'Capital One Arena', '{basketball_nba}'),
  ('nba-chase.webp', 'Chase Center', '{basketball_nba}'),
  ('nba-cryptocom.webp', 'Crypto.com Arena', '{basketball_nba}'),
  ('nba-delta-center.webp', 'Delta Center', '{basketball_nba}'),
  ('nba-fedex.webp', 'FedExForum', '{basketball_nba}'),
  ('nba-fiserv.webp', 'Fiserv Forum', '{basketball_nba}'),
  ('nba-frost-bank.webp', 'Frost Bank Center', '{basketball_nba}'),
  ('nba-gainbridge-fieldhouse.webp', 'Gainbridge Fieldhouse', '{basketball_nba}'),
  ('nba-golden-1.webp', 'Golden 1 Center', '{basketball_nba}'),
  ('nba-intuit-dome.webp', 'Intuit Dome', '{basketball_nba}'),
  ('nba-kaseya-center.webp', 'Kaseya Center', '{basketball_nba}'),
  ('nba-kia-center.webp', 'Kia Center', '{basketball_nba}'),
  ('nba-little-caesars.webp', 'Little Caesars Arena', '{basketball_nba}'),
  ('nba-msg.webp', 'Madison Square Garden', '{basketball_nba}'),
  ('nba-moda.webp', 'Moda Center', '{basketball_nba}'),
  ('nba-mortgage.webp', 'Rocket Mortgage FieldHouse', '{basketball_nba}'),
  ('nba-oracle.webp', 'Oracle Arena', '{basketball_nba}'),
  ('nba-paycom-center.webp', 'Paycom Center', '{basketball_nba}'),
  ('nba-rocket.webp', 'Toyota Center', '{basketball_nba}'),
  ('nba-scotiabank.webp', 'Scotiabank Arena', '{basketball_nba}'),
  ('nba-smoothie-king.webp', 'Smoothie King Center', '{basketball_nba}'),
  ('nba-state-farm.webp', 'State Farm Arena', '{basketball_nba}'),
  ('nba-target-center.webp', 'Target Center', '{basketball_nba}'),
  ('nba-the-garden.webp', 'TD Garden', '{basketball_nba}'),
  ('nba-toyota.webp', 'Toyota Center', '{basketball_nba}'),
  ('nba-united.webp', 'United Center', '{basketball_nba}'),
  ('nba-xfinity-mobile-center.webp', 'Spectrum Center', '{basketball_nba}'),
  ('mlb-american-family.webp', 'American Family Field', '{baseball_mlb}'),
  ('mlb-angel.webp', 'Angel Stadium', '{baseball_mlb}'),
  ('mlb-busch.webp', 'Busch Stadium', '{baseball_mlb}'),
  ('mlb-camden-yards.webp', 'Camden Yards', '{baseball_mlb}'),
  ('mlb-chase.webp', 'Chase Field', '{baseball_mlb}'),
  ('mlb-citi-field.webp', 'Citi Field', '{baseball_mlb}'),
  ('mlb-citizens-bank.webp', 'Citizens Bank Park', '{baseball_mlb}'),
  ('mlb-comerica.webp', 'Comerica Park', '{baseball_mlb}'),
  ('mlb-coors.webp', 'Coors Field', '{baseball_mlb}'),
  ('mlb-globe-life-field.webp', 'Globe Life Field', '{baseball_mlb}'),
  ('mlb-great-american-ball-park.webp', 'Great American Ball Park', '{baseball_mlb}'),
  ('mlb-kauffman.webp', 'Kauffman Stadium', '{baseball_mlb}'),
  ('mlb-loandepot.webp', 'LoanDepot Park', '{baseball_mlb}'),
  ('mlb-minute-maid.webp', 'Minute Maid Park', '{baseball_mlb}'),
  ('mlb-nationals.webp', 'Nationals Park', '{baseball_mlb}'),
  ('mlb-pnc.webp', 'PNC Park', '{baseball_mlb}'),
  ('mlb-petco.webp', 'Petco Park', '{baseball_mlb}'),
  ('mlb-progressive.webp', 'Progressive Field', '{baseball_mlb}'),
  ('mlb-rate.webp', 'Guaranteed Rate Field', '{baseball_mlb}'),
  ('mlb-rogers-centre.webp', 'Rogers Centre', '{baseball_mlb}'),
  ('mlb-sutter-health.webp', 'Sutter Health Park', '{baseball_mlb}'),
  ('mlb-tmobile.webp', 'T-Mobile Park', '{baseball_mlb}'),
  ('mlb-target.webp', 'Target Field', '{baseball_mlb}'),
  ('mlb-tropicana.webp', 'Tropicana Field', '{baseball_mlb}'),
  ('mlb-truist.webp', 'Truist Park', '{baseball_mlb}'),
  ('mlb-vegas-as-stadium.webp', 'Vegas A''s Stadium', '{baseball_mlb}'),
  ('mlb-yankee.webp', 'Yankee Stadium', '{baseball_mlb}')
ON CONFLICT (filename) DO UPDATE SET label = EXCLUDED.label, formats = EXCLUDED.formats;
